In [2]:
pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\minky\appdata\local\programs\python\python39\lib\site-packages (2.2.2)
Requirement already satisfied: openpyxl in c:\users\minky\appdata\local\programs\python\python39\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.22.4 in c:\users\minky\appdata\local\programs\python\python39\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\minky\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\minky\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\minky\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: et-xmlfile in c:\users\minky\appdata\local\programs\python\python39\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\minky\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

# df = pd.read_csv("data\\389개의 감정단어")
# emotionset = df.drop(['원형성', '친숙성'], axis=1)
emotionset = pd.read_csv("data\\새로운_단어.csv")

In [5]:
emotionset = emotionset.drop(['Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'], axis=1)
emotionset

          단어  쾌-불쾌   활성화
0    가라앉는 듯한  2.70  2.93
1        가벼운  5.33  2.85
2        가뿐한  5.25  2.61
3      가슴 아픈  2.18  2.98
4    가슴이 저미는  2.18  2.22
..       ...   ...   ...
151      흐믓한  5.85  5.02
152      흔쾌한  6.06  5.26
153      희망찬  5.39  5.12
154     희망하는  5.19  5.07
155       힘찬  5.78  5.24

[156 rows x 3 columns]

In [6]:
import numericalization as numer

emo_rgb = []
for i in range(len(emotionset)):
    # print(emotionset['단어'][i])
    valence = emotionset['쾌-불쾌'][i]
    arousal = emotionset['활성화'][i]
    color = numer.rgb(valence, arousal)
    emo_rgb.append(color.numericalization())

In [7]:
emo_rgb

[{'r': 0, 'g': 148, 'b': 202, 'hexa': '0094ca'},
 {'r': 36, 'g': 0, 'b': 207, 'hexa': '2400cf'},
 {'r': 28, 'g': 0, 'b': 192, 'hexa': '1c00c0'},
 {'r': 0, 'g': 41, 'b': 204, 'hexa': '0029cc'},
 {'r': 0, 'g': 41, 'b': 166, 'hexa': '0029a6'},
 {'r': 165, 'g': 172, 'b': 0, 'hexa': 'a5ac00'},
 {'r': 189, 'g': 174, 'b': 0, 'hexa': 'bdae00'},
 {'r': 236, 'g': 197, 'b': 0, 'hexa': 'ecc500'},
 {'r': 196, 'g': 195, 'b': 7, 'hexa': 'c4c307'},
 {'r': 184, 'g': 35, 'b': 53, 'hexa': 'b82335'},
 {'r': 196, 'g': 187, 'b': 0, 'hexa': 'c4bb00'},
 {'r': 231, 'g': 198, 'b': 0, 'hexa': 'e7c600'},
 {'r': 250, 'g': 250, 'b': 0, 'hexa': 'fafa00'},
 {'r': 199, 'g': 199, 'b': 31, 'hexa': 'c7c71f'},
 {'r': 201, 'g': 193, 'b': 32, 'hexa': 'c9c120'},
 {'r': 226, 'g': 185, 'b': 0, 'hexa': 'e2b900'},
 {'r': 182, 'g': 171, 'b': 45, 'hexa': 'b6ab2d'},
 {'r': 244, 'g': 209, 'b': 0, 'hexa': 'f4d100'},
 {'r': 171, 'g': 35, 'b': 3, 'hexa': 'ab2303'},
 {'r': 203, 'g': 203, 'b': 23, 'hexa': 'cbcb17'},
 {'r': 195, 'g': 75, 'b': 16, 'hexa': 'c34b10'},
 {'r': 176, 'g': 14, 'b': 66, 'hexa': 'b00e42'},
 {'r': 252, 'g': 252, 'b': 0, 'hexa': 'fcfc00'},
 {'r': 216, 'g': 193, 'b': 92, 'hexa': 'd8c15c'},
 {'r': 211, 'g': 175, 'b': 0, 'hexa': 'd3af00'},
 {'r': 189, 'g': 33, 'b': 79, 'hexa': 'bd214f'},
 {'r': 228, 'g': 194, 'b': 0, 'hexa': 'e4c200'},
 {'r': 197, 'g': 39, 'b': 97, 'hexa': 'c52761'},
 {'r': 200, 'g': 180, 'b': 79, 'hexa': 'c8b44f'},
 {'r': 191, 'g': 191, 'b': 52, 'hexa': 'bfbf34'},
 {'r': 185, 'g': 31, 'b': 66, 'hexa': 'b91f42'},
 {'r': 156, 'g': 7, 'b': 13, 'hexa': '9c070d'},
 {'r': 193, 'g': 79, 'b': 29, 'hexa': 'c14f1d'},
 {'r': 140, 'g': 0, 'b': 100, 'hexa': '8c0064'},
 {'r': 231, 'g': 75, 'b': 0, 'hexa': 'e74b00'},
 {'r': 218, 'g': 79, 'b': 100, 'hexa': 'da4f64'},
 {'r': 184, 'g': 35, 'b': 53, 'hexa': 'b82335'},
 {'r': 227, 'g': 202, 'b': 100, 'hexa': 'e3ca64'},
 {'r': 13, 'g': 175, 'b': 13, 'hexa': '0daf0d'},
 {'r': 231, 'g': 196, 'b': 0, 'hexa': 'e7c400'},
 {'r': 181, 'g': 193, 'b': 95, 'hexa': 'b5c15f'},
 {'r': 250, 'g': 37, 'b': 0, 'hexa': 'fa2500'},
 {'r': 21, 'g': 0, 'b': 21, 'hexa': '150015'},
 {'r': 238, 'g': 203, 'b': 0, 'hexa': 'eecb00'},
 {'r': 214, 'g': 46, 'b': 0, 'hexa': 'd62e00'},
 {'r': 239, 'g': 239, 'b': 0, 'hexa': 'efef00'},
 {'r': 221, 'g': 183, 'b': 0, 'hexa': 'ddb700'},
 {'r': 199, 'g': 199, 'b': 195, 'hexa': 'c7c7c3'},
 {'r': 189, 'g': 189, 'b': 169, 'hexa': 'bdbda9'},
 {'r': 219, 'g': 184, 'b': 0, 'hexa': 'dbb800'},
 {'r': 155, 'g': 154, 'b': 5, 'hexa': '9b9a05'},
 {'r': 179, 'g': 179, 'b': 183, 'hexa': 'b3b3b7'},
 {'r': 234, 'g': 234, 'b': 0, 'hexa': 'eaea00'},
 {'r': 165, 'g': 31, 'b': 0, 'hexa': 'a51f00'},
 {'r': 244, 'g': 106, 'b': 0, 'hexa': 'f46a00'},
 {'r': 181, 'g': 27, 'b': 58, 'hexa': 'b51b3a'},
 {'r': 188, 'g': 232, 'b': 0, 'hexa': 'bce800'},
 {'r': 177, 'g': 45, 'b': 7, 'hexa': 'b12d07'},
 {'r': 174, 'g': 35, 'b': 12, 'hexa': 'ae230c'},
 {'r': 237, 'g': 202, 'b': 0, 'hexa': 'edca00'},
 {'r': 231, 'g': 231, 'b': 0, 'hexa': 'e7e700'},
 {'r': 173, 'g': 99, 'b': 0, 'hexa': 'ad6300'},
 {'r': 228, 'g': 191, 'b': 0, 'hexa': 'e4bf00'},
 {'r': 193, 'g': 183, 'b': 42, 'hexa': 'c1b72a'},
 {'r': 217, 'g': 200, 'b': 65, 'hexa': 'd9c841'},
 {'r': 199, 'g': 219, 'b': 0, 'hexa': 'c7db00'},
 {'r': 163, 'g': 14, 'b': 14, 'hexa': 'a30e0e'},
 {'r': 228, 'g': 194, 'b': 0, 'hexa': 'e4c200'},
 {'r': 174, 'g': 47, 'b': 0, 'hexa': 'ae2f00'},
 {'r': 244, 'g': 106, 'b': 0, 'hexa': 'f46a00'},
 {'r': 159, 'g': 95, 'b': 0, 'hexa': '9f5f00'},
 {'r': 229, 'g': 229, 'b': 0, 'hexa': 'e5e500'},
 {'r': 225, 'g': 67, 'b': 0, 'hexa': 'e14300'},
 {'r': 254, 'g': 254, 'b': 0, 'hexa': 'fefe00'},
 {'r': 219, 'g': 195, 'b': 99, 'hexa': 'dbc363'},
 {'r': 230, 'g': 194, 'b': 0, 'hexa': 'e6c200'},
 {'r': 227, 'g': 227, 'b': 0, 'hexa': 'e3e300'},
 {'r': 61, 'g': 0, 'b': 50, 'hexa': '3d0032'},
 {'r': 195, 'g': 75, 'b': 16, 'hexa': 'c34b10'},
 {'r': 235, 'g': 235, 'b': 0, 'hexa': 'ebeb00'},
 {'r': 219, 'g': 99, 'b': 65, 'hexa': 'db6341'},
 {'r': 130, 'g': 0, 'b': 27, 'hexa': '82001b'},
 {'r': 171, 'g': 42, 'b': 0, 'hexa': 'ab2a00'},
 {'r': 167, 'g': 220, 'b': 0, 'hexa': 'a7dc00'},
 {'r': 164, 'g': 220, 'b': 0, 'hexa': 'a4dc00'},
 {'r': 5, 'g': 123, 'b': 5, 'hexa': '057b05'},
 {'r': 28, 'g': 142, 'b': 28, 'hexa': '1c8e1c'},
 {'r': 154, 'g': 77, 'b': 0, 'hexa': '9a4d00'},
 {'r': 225, 'g': 225, 'b': 0, 'hexa': 'e1e100'},
 {'r': 201, 'g': 198, 'b': 13, 'hexa': 'c9c60d'},
 {'r': 170, 'g': 6, 'b': 58, 'hexa': 'aa063a'},
 {'r': 58, 'g': 0, 'b': 57, 'hexa': '3a0039'},
 {'r': 204, 'g': 26, 'b': 0, 'hexa': 'cc1a00'},
 {'r': 169, 'g': 195, 'b': 0, 'hexa': 'a9c300'},
 {'r': 201, 'g': 248, 'b': 0, 'hexa': 'c9f800'},
 {'r': 169, 'g': 148, 'b': 0, 'hexa': 'a99400'},
 {'r': 228, 'g': 73, 'b': 0, 'hexa': 'e44900'},
 {'r': 238, 'g': 93, 'b': 0, 'hexa': 'ee5d00'},
 {'r': 204, 'g': 75, 'b': 53, 'hexa': 'cc4b35'},
 {'r': 180, 'g': 40, 'b': 26, 'hexa': 'b4281a'},
 {'r': 117, 'g': 193, 'b': 0, 'hexa': '75c100'},
 {'r': 205, 'g': 195, 'b': 40, 'hexa': 'cdc328'},
 {'r': 223, 'g': 101, 'b': 78, 'hexa': 'df654e'},
 {'r': 81, 'g': 193, 'b': 81, 'hexa': '51c151'},
 {'r': 54, 'g': 0, 'b': 53, 'hexa': '360035'},
 {'r': 212, 'g': 0, 'b': 21, 'hexa': 'd40015'},
 {'r': 197, 'g': 241, 'b': 0, 'hexa': 'c5f100'},
 {'r': 104, 'g': 127, 'b': 104, 'hexa': '687f68'},
 {'r': 191, 'g': 231, 'b': 0, 'hexa': 'bfe700'},
 {'r': 211, 'g': 79, 'b': 75, 'hexa': 'd34f4b'},
 {'r': 158, 'g': 155, 'b': 0, 'hexa': '9e9b00'},
 {'r': 80, 'g': 0, 'b': 11, 'hexa': '50000b'},
 {'r': 242, 'g': 102, 'b': 0, 'hexa': 'f26600'},
 {'r': 158, 'g': 185, 'b': 0, 'hexa': '9eb900'},
 {'r': 206, 'g': 0, 'b': 0, 'hexa': 'ce0000'},
 {'r': 147, 'g': 0, 'b': 0, 'hexa': '930000'},
 {'r': 229, 'g': 192, 'b': 0, 'hexa': 'e5c000'},
 {'r': 156, 'g': 202, 'b': 0, 'hexa': '9cca00'},
 {'r': 223, 'g': 186, 'b': 0, 'hexa': 'dfba00'},
 {'r': 212, 'g': 42, 'b': 0, 'hexa': 'd42a00'},
 {'r': 204, 'g': 167, 'b': 0, 'hexa': 'cca700'},
 {'r': 241, 'g': 204, 'b': 0, 'hexa': 'f1cc00'},
 {'r': 223, 'g': 186, 'b': 0, 'hexa': 'dfba00'},
 {'r': 246, 'g': 246, 'b': 0, 'hexa': 'f6f600'},
 {'r': 241, 'g': 241, 'b': 0, 'hexa': 'f1f100'},
 {'r': 192, 'g': 223, 'b': 0, 'hexa': 'c0df00'},
 {'r': 250, 'g': 218, 'b': 0, 'hexa': 'fada00'},
 {'r': 197, 'g': 193, 'b': 16, 'hexa': 'c5c110'},
 {'r': 204, 'g': 189, 'b': 61, 'hexa': 'ccbd3d'},
 {'r': 220, 'g': 197, 'b': 92, 'hexa': 'dcc55c'},
 {'r': 198, 'g': 98, 'b': 0, 'hexa': 'c66200'},
 {'r': 160, 'g': 145, 'b': 0, 'hexa': 'a09100'},
 {'r': 205, 'g': 185, 'b': 81, 'hexa': 'cdb951'},
 {'r': 246, 'g': 109, 'b': 0, 'hexa': 'f66d00'},
 {'r': 168, 'g': 15, 'b': 32, 'hexa': 'a80f20'},
 {'r': 115, 'g': 0, 'b': 115, 'hexa': '730073'},
 {'r': 101, 'g': 0, 'b': 100, 'hexa': '650064'},
 {'r': 219, 'g': 55, 'b': 0, 'hexa': 'db3700'},
 {'r': 199, 'g': 234, 'b': 0, 'hexa': 'c7ea00'},
 {'r': 211, 'g': 191, 'b': 81, 'hexa': 'd3bf51'},
 {'r': 83, 'g': 175, 'b': 83, 'hexa': '53af53'},
 {'r': 206, 'g': 190, 'b': 62, 'hexa': 'cebe3e'},
 {'r': 155, 'g': 3, 'b': 3, 'hexa': '9b0303'},
 {'r': 204, 'g': 167, 'b': 0, 'hexa': 'cca700'},
 {'r': 158, 'g': 11, 'b': 21, 'hexa': '9e0b15'},
 {'r': 181, 'g': 23, 'b': 66, 'hexa': 'b51742'},
 {'r': 187, 'g': 32, 'b': 71, 'hexa': 'bb2047'},
 {'r': 190, 'g': 49, 'b': 52, 'hexa': 'be3134'},
 {'r': 246, 'g': 246, 'b': 0, 'hexa': 'f6f600'},
 {'r': 231, 'g': 194, 'b': 0, 'hexa': 'e7c200'},
 {'r': 236, 'g': 89, 'b': 0, 'hexa': 'ec5900'},
 {'r': 177, 'g': 4, 'b': 89, 'hexa': 'b10459'},
 {'r': 167, 'g': 28, 'b': 15, 'hexa': 'a71c0f'},
 {'r': 171, 'g': 15, 'b': 41, 'hexa': 'ab0f29'},
 {'r': 163, 'g': 10, 'b': 22, 'hexa': 'a30a16'},
 {'r': 187, 'g': 27, 'b': 82, 'hexa': 'bb1b52'}]

In [8]:
rgb = pd.DataFrame(emo_rgb)

In [9]:
emotion_rgb = pd.concat([emotionset, rgb], axis=1)

In [10]:
emotion_rgb

          단어  쾌-불쾌   활성화    r    g    b    hexa
0    가라앉는 듯한  2.70  2.93    0  148  202  0094ca
1        가벼운  5.33  2.85   36    0  207  2400cf
2        가뿐한  5.25  2.61   28    0  192  1c00c0
3      가슴 아픈  2.18  2.98    0   41  204  0029cc
4    가슴이 저미는  2.18  2.22    0   41  166  0029a6
..       ...   ...   ...  ...  ...  ...     ...
151      흐믓한  5.85  5.02  177    4   89  b10459
152      흔쾌한  6.06  5.26  167   28   15  a71c0f
153      희망찬  5.39  5.12  171   15   41  ab0f29
154     희망하는  5.19  5.07  163   10   22  a30a16
155       힘찬  5.78  5.24  187   27   82  bb1b52

[156 rows x 7 columns]

In [11]:
# emotion_rgb.to_excel('감정_rgb_2.xlsx', index=False)

In [4]:
emotionset = pd.read_excel("data\\rgb\\감정_rgb.xlsx")

In [5]:
emotionset = emotionset.drop(['hexa'], axis=1)
emotionset = emotionset.drop(['쾌-불쾌','활성화'], axis=1)

In [6]:
emotionset

          단어    r    g    b
0       가뜬하다  201   54   83
1    가라앉는 듯한    0  148  202
2       가련하다  164  159   19
3        가벼운   36    0  207
4        가뿐한   28    0  192
..       ...  ...  ...  ...
540     희망하는  163   10   22
541       희비  241  241    0
542       희열  186   48   35
543   희희낙락하다  242  213    0
544       힘찬  187   27   82

[545 rows x 4 columns]

# 몇개 뽑아서 평균 내고 진짜 오늘의 색처럼 표현해보기

In [7]:
tmp = emotionset.iloc[[48,49,57,59,66]]
tmp

       단어    r    g    b
48   고독하다    0   80  178
49    고립감   30   21   30
57    골나다  167   63    0
59     공포    7   68    0
66  구역질나는  244  209    0

In [25]:
tmp_rgb = []
len = tmp.shape[0]
print(len)
first = len/10
print(first)
last = (1-first) / (len-1)
print(last)

red = tmp['r']
red = str((int(sum(tmp['r'])) / len))
green = str((int(sum(tmp['g']) / len)))
blue = str((int(sum(tmp['b']) / len)))

print(red)
print(green)
print(blue)

5
0.5
0.125
89.6
88
41